# image will be published to ghcr.io/akippnn/starlight
name: starlight
description: My own personal Fedora Sericea image spin

base-image: ghcr.io/ublue-os/sericea-main
image-version: 39 # NOTE: Change version for Fedora 40 and so on

modules:
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-39/atim-starship-fedora-39.repo
      - https://copr.fedorainfracloud.org/coprs/eddsalkield/swaylock-effects/repo/fedora-39/eddsalkield-swaylock-effects-fedora-39.repo
      # NOTE: change "fedora-39" string for image-version changes
    install:
      # - micro
      # dm + deps
      - sddm-wayland-generic
      - qt5-qtquickcontrols2
      - qt5-qtsvg
      # shell
      - fish
      - starship
      # de + deps
      - hyprland
      - mako
      - xdg-desktop-portal-hyprland
      - polkit-kde
      - waybar
      - wl-clipboard
      - swaylock-effects
      - qt5-qtwayland
      - qt6-qtwayland
    remove:
      # de
      - sway
      - swayidle
      - swaybg
      - swaylock
      - sway-config-fedora
      - sway-systemd
      - sddm-wayland-sway
      - firefox
      - firefox-langpacks

  - type: files
    files:
      - usr: /usr
      # /etc should be inside /usr/etc

  - type: bling
    install:
      - justfiles
      - nix-installer
      - ublue-os-wallpapers
      # - ublue-update # https://github.com/ublue-os/ublue-update
      # - 1password # install 1Password (stable) and `op` CLI tool
      # - dconf-update-service # a service unit that updates the dconf db on boot
      # - devpod # https://devpod.sh/ as an rpm
      # - gnome-vrr # enables gnome-vrr for your image
      # - container-tools # installs container-related tools onto /usr/bin: kind, kubectx, docker-compose and kubens
      - laptop # installs TLP and configures your system for laptop usage
      - flatpaksync # allows synchronization of user-installed flatpaks, see separate documentation section

  - type: yafti
    custom-flatpaks: # this section is optional
      - Warehouse: io.github.flattool.Warehouse
      # - Celluloid: io.github.celluloid_player.Celluloid
      # - Krita: org.kde.krita

  - type: script
    scripts:
      - signing.sh
