#!/usr/bin/env bash

conf_file="$HOME/.config/hypr/hyprland.conf"
do_something=1

if [[ ! -f "$conf_file" ]]; then
    do_something=0
elif grep -q -E "^[[:blank:]]*autogenerated[[:blank:]]*=[[:blank:]]*1[[:blank:]]*$" "$conf_file"; then
    do_something=0
fi

if [[ $do_something -eq 0 ]]; then
    echo "" > $conf_file
fi
