/**
 * A Theme is a set of options that will be applied
 * ontop of the default values. see options.js for possible options
 */
import { Theme, WP, lightColors } from './settings/theme.js';

export default [
    Theme({
        "name": "starlight",
        "icon": "🌠",
        "spacing": 8,
        "padding": 10,
        "radii": 12,
        "popover_padding_multiplier": 1.4,
        "color.red": "#e55f86",
        "color.green": "#00D787",
        "color.yellow": "#EBFF71",
        "color.blue": "#51a4e7",
        "color.magenta": "#9077e7",
        "color.teal": "#51e6e6",
        "color.orange": "#E79E64",
        "theme.scheme": "dark",
        "theme.bg": "transparentize(#171717, 0.3)",
        "theme.fg": "#eeeeee",
        "theme.accent.accent": "$red",
        "theme.accent.fg": "#141414",
        "theme.accent.gradient": "to right, $accent, lighten($accent, 6%)",
        "theme.widget.bg": "$fg-color",
        "theme.widget.opacity": 95,
        "border.color": "$fg-color",
        "border.opacity": 97,
        "border.width": 1,
        "hypr.inactive_border": "rgba(333333ff)",
        "hypr.wm_gaps_multiplier": 2.4,
        "font.font": "Ubuntu Nerd Font Regular",
        "font.mono": "Mononoki Nerd Font Regular",
        "font.size": 13,
        "applauncher.width": 500,
        "applauncher.height": 500,
        "applauncher.icon_size": 52,
        "bar.position": "bottom",
        "bar.style": "separated",
        "bar.flat_buttons": false,
        "bar.separators": false,
        "bar.icon": "distro-icon",
        "battery.bar.show_icon": true,
        "battery.bar.width": 68,
        "battery.bar.height": 14,
        "battery.bar.full": true,
        "battery.low": 30,
        "battery.medium": 50,
        "desktop.wallpaper.fg": "#fff",
        "desktop.wallpaper.img": WP + "starlight.jpg",
        "desktop.avatar": "/var/lib/AccountsService/icons/aki",
        "desktop.screen_corners": false,
        "desktop.clock.enable": false,
        "desktop.clock.position": "center center",
        "desktop.drop_shadow": true,
        "desktop.shadow": "rgba(0, 0, 0, .6)",
        "desktop.dock.icon_size": 56,
        "desktop.dock.pinned_apps": [
            "firefox",
            "org.wezfurlong.wezterm",
            "org.gnome.Nautilus",
            "org.gnome.Calendar",
            "obsidian",
            "transmission-gtk",
            "caprine",
            "teams-for-linux",
            "discord",
            "spotify",
            "com.usebottles.bottles",
            "org.gnome.Software"
        ],
        "notifications.black_list": [
            "spotify"
        ],
        "notifications.position": [
            "bottom"
        ],
        "notifications.width": 450,
        "dashboard.sys_info_size": 70,
        "mpris.black_list": [
            "Caprine"
        ],
        "mpris.preferred": "spotify",
        "workspaces": 10
    }),
    Theme({
        name: 'Leaves',
        icon: '󰌪',
        'desktop.wallpaper.img': WP + 'leaves.jpg',
        'theme.accent.accent': '$green',
        'theme.accent.gradient': 'to right, $accent, darken($accent, 14%)',
        'theme.widget.opacity': 92,
        'border.opacity': 86,
        'theme.bg': 'transparentize(#171717, 0.3)',
        'bar.style': 'floating',
        'radii': 0,
    }),
    Theme({
        name: 'Space',
        icon: '',
        'desktop.wallpaper.img': WP + 'space.jpg',
        'spacing': 11,
        'padding': 10,
        'radii': 12,
        'theme.accent.accent': '$magenta',
        'desktop.screen_corners': false,
        'desktop.clock.enable': false,
        'bar.separators': false,
        'theme.bg': 'transparentize(#171717, 0.3)',
        'theme.widget.opacity': 95,
        'bar.flat_buttons': false,
    }),
];
